services:
  cloudary-postgres:
    image: postgres:16
    container_name: cloudary_pg_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudary
    ports:
      - "5432:5432"
    volumes:
      - cloudary_vol_pg:/var/lib/postgresql/data
    networks:
      - cloudary-network
  cloudary-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cloudary_pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - cloudary_vol_pgadmin:/var/lib/pgadmin
    networks:
      - cloudary-network
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - cloudary_redis_data:/data
    networks:
      - cloudary-network

networks:
  cloudary-network:
    driver: bridge

volumes:
  cloudary_vol_pg:
  cloudary_vol_pgadmin:
  cloudary_redis_data: